name: IG build entry workflow

# Setup:
# 1. Copy this file and name it to match the IG folder name to help relate the file to the IG. The file name it not
#    important but it helps to match the IG folder name. Remove the .off suffix if there is one.
# 2. Set the env variables to match your setup.
# 3. Adjust the paths under the `on.push.paths`  and `on.pull_request_target.paths` keys to match your IG's directory.
# 4. Set up a GitHub Actions secret in this repository for the PAT token to write to the publishing repository so the build can push to it. the secrete is named secrets.PUBLISHER_IO
# 5. Enable GitHub actions and write access to this repository.
# 6.
env:
  IG_ROOT: "fw-ig/minimal-r401"  # The relative folder path of the IG root directory
  DOCKER_PUBLISHER_TAG: 1.1.118-latest  # The Docker tag for the Publisher version wanted for the build from: https://hub.docker.com/repository/docker/sessaid/ig-publisher
  PUBLISHER_ARGS: "-ig /ig/ig.ini"  # the publisher command line arguments
  IO_OWNER:  #  The owner of a GitHub repository that will be used for publishing the built IG's output
  IO_REPO:  # The repository to publish to
  IO_BRANCH: gh-pages  # The branch to publish to
  IO_PATH_PREFIX: ''  # An optional path prefix (from the root of the repo) to publish to. No leading slash but with a trailing slash

defaults:
  run:
    shell: bash

concurrency:
  group: ig-build

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master, dev ]
    paths:
      - fw-ig/minimal-r401/**
  pull_request_target:
    paths:
      - fw-ig/minimal-r401/**

jobs:

  # Do any setup needed to create job output parameters needed to the later build job
  vars:
    name: Build vars
    runs-on: ubuntu-latest
    outputs:
      owner-repo: ${{ steps.vars.outputs.owner-repo }}
      ref: ${{ steps.vars.outputs.ref }}
      try-merge: ${{ steps.vars.outputs.try-merge }}
      base-ref: ${{ steps.vars.outputs.base-ref }}
      pr-number: ${{ steps.vars.outputs.pr-number }}
      ig-root: ${{ steps.vars.outputs.ig-root }}
      publisher-args: ${{ steps.vars.outputs.publisher-args }}
      docker-publisher-tag: ${{ steps.vars.outputs.docker-publisher-tag }}
      io-owner: ${{ steps.vars.outputs.io-owner }}
      io-repo: ${{ steps.vars.outputs.io-repo }}
      io-branch: ${{ steps.vars.outputs.io-branch }}
      io-path: ${{ steps.vars.outputs.io-path }}

    steps:
      - id: vars
        run: |

          if [ "${{ github.event_name }}" = "push" ]; then
            echo "::set-output name=owner-repo::${{ github.repository }}"
            echo "::set-output name=ref::${{ github.ref_name }}"
            echo "::set-output name=try-merge::false"
            echo "::set-output name=base-ref::"
            echo "::set-output name=pr-number::1"
            echo "::set-output name=ig-root::${{ env.IG_ROOT }}"
            echo "::set-output name=publisher-args::${{ env.PUBLISHER_ARGS }}"
            echo "::set-output name=docker-publisher-tag::${{ env.DOCKER_PUBLISHER_TAG }}"
            echo "::set-output name=io-owner::${{ env.IO_OWNER }}"
            echo "::set-output name=io-repo::${{ env.IO_REPO }}"
            echo "::set-output name=io-branch::${{ env.IO_BRANCH }}"
            echo "::set-output name=io-path::${{ env.IO_PATH_PREFIX }}${{ env.IG_ROOT }}/branch/${{ github.ref_name }}"

          elif [ "${{ github.event_name }}" = "pull_request_target" ]; then
            echo "::set-output name=owner-repo::${{ github.event.pull_request.head.repo.full_name }}"
            echo "::set-output name=ref::${{ github.event.pull_request.head.ref }}"
            echo "::set-output name=try-merge::true"
            echo "::set-output name=base-ref::${{ github.event.pull_request.base.ref }}"
            echo "::set-output name=pr-number::${{ github.event.number }}"
            echo "::set-output name=ig-root::${{ env.IG_ROOT }}"
            echo "::set-output name=publisher-args::${{ env.PUBLISHER_ARGS }}"
            echo "::set-output name=docker-publisher-tag::${{ env.DOCKER_PUBLISHER_TAG }}"
            echo "::set-output name=io-owner::${{ env.IO_OWNER }}"
            echo "::set-output name=io-repo::${{ env.IO_REPO }}"
            echo "::set-output name=io-branch::${{ env.IO_BRANCH }}"
            echo "::set-output name=io-path::${{ env.IO_PATH_PREFIX }}${{ env.IG_ROOT }}/pr-${{ github.event.number }}/${{ github.event.pull_request.base.ref }}/FROM-${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}"

          else
           echo EXITING DUE TO UNKNOWN EVENT NAME.
           exit 1
          fi

  build:
    needs: vars
    uses: ./.github/workflows/fw-ig-build-callable.yml
    secrets:
      output-token: ${{ secrets.PUBLISHER_IO }}
    with:
      owner-repo: ${{ needs.vars.outputs.owner-repo }}
      ref: ${{ needs.vars.outputs.ref }}

      ig-root: ${{ needs.vars.outputs.ig-root }}
      publisher-args: ${{ needs.vars.outputs.publisher-args }}
      docker-publisher-tag: ${{ needs.vars.outputs.docker-publisher-tag }}
      base-ref: ${{ needs.vars.outputs.base-ref }}

      io-owner: ${{ needs.vars.outputs.io-owner }}
      io-repo: ${{ needs.vars.outputs.io-repo }}
      io-branch: ${{ needs.vars.outputs.io-branch }}
      io-path: ${{ needs.vars.outputs.io-path }}
